BINDIR:=./
BITMAPSDIR:=./bitmaps/
EXECBIN:=\.\/
DBDIR:=./
CFLAGS:=-Os -I.
LDFLAGS:=
VERSION:=1.0
SOURCES:=cailogin.c file.c filters.c image.c
OBJECTS:=cailogin.o file.o filters.o image.o

TIMETHRESHOLD:=600
MAXDBENTRIES:=300

all: clean example/ vars.h example/login.cgi cailogin cailogin.cgi
	cp cailogin ./example/
	cp cailogin.cgi ./example/
	cp -a bitmaps ./example/
	cp cailogin.db ./example/
	chmod 666 ./example/cailogin.db
	chown apache:apache ./example/cailogin.db

example/:
	mkdir example

vars.h:
	echo "#define EXECBIN \"${BINDIR}cailogin\"" > vars.h
	echo "#define BITMAPSDIR \"${BITMAPSDIR}\"" >> vars.h
	echo "#define DBDIR \"${DBDIR}\"" >> vars.h
	echo "#define VERSION \"${VERSION}\"" >> vars.h
	echo "#define TIMETHRESHOLD ${TIMETHRESHOLD}" >> vars.h
	echo "#define MAXDBENTRIES ${MAXDBENTRIES}" >> vars.h

example/login.cgi:
	cp login.cgi ./example/
	sed -i 's/^EXECBIN.*$$/EXECBIN=${EXECBIN}/g' example/login.cgi

cailogin: ${OBJECTS}
	gcc -o cailogin ${OBJECTS}

cailogin.cgi: cailogin.cgi.o
	gcc -o cailogin.cgi cailogin.cgi.o

cailogin.cgi.o: cailogin.cgi.c
	gcc -c cailogin.cgi.c

${OBJECTS}: ${SOURCES}
	gcc -c ${SOURCES}

clean:
	-rm *.o
	-rm vars.h
	-rm cailogin cailogin.cgi
	-rm -rf example/

strip:
	strip -s cailogin
	-strip -s cailogin.cgi
